const konten = {

    art: 'Jurusan Sistem Informasi' ,
    indo: 'Jurusan Sistem Informasi adalah bidang keilmuan yang menggabungkan ilmu komputer dengan bisnis dan manajemen. Di prodi ini kamu akan belajar gimana mengidentifikasi kebutuhan dan proses bisnis perusahaan berdasarkan data-data yang dimiliki perusahan, kemudian merancang sistem yang sesuai dengan kebutuhan perusahaan. Jadi, selain belajar teknik pemrograman, kamu juga dituntut untuk mempelajari proses bisnis yang ada di perusahaan. Oleh karena itu, lulusan Prodi Sistem Informasi diharapkan dapat mengembangkan sebuah sistem pengolahan data dari berbagai sumber untuk dapat disajikan sebagai informasi yang bermanfaat bagi perusahaan. Apakah kamu masih bingung lulusan Jurusan Sistem Informasi akan bekerja apa dan dimana? Tenang saja, karena lulusan prodi ini memiliki peluang karier yang sangat besar. Jenis dan jenjang karier yang ditawarkan sangat bervariasi dan menjanjikan. Jadi, ilmu dan keterampilan yang kamu dapatkan di bangku kuliah sudah selayaknya kamu banggakan, karena menjadi modal yang sangat berharga di pasar tenaga kerja. Lulusan Sistem Informasi akan sangat dibutuhkan oleh perusahaan untuk pengembangkan sistem yang menjembatani programmer dengan user. Apa saja prospek kerja Prodi Sistem Informasi? Perlu kamu ketahui lebih dulu, bahwa pekerjaan di bidang sistem informasi tergolong pekerjaan dengan bayaran tertinggi dan paling dibutuhkan hingga 10 tahun ke depan. Pilihan kariernya pun sangat bervariasi, seperti System Analyst, Computer System Administrator, IT Manager dan Web DeveloperData Scientist, Information System Management, Software Developer, Information Security Analyst, serta Application Analyst. Secara umum, rata-rata gaji awal lulusan Sistem Informasi berada pada kisaran Rp5.000.000, dengan pekerjaan sebagai staf bidang teknologi informasi di suatu perusahaan. Meskipun begitu, perolehan gaji jyang lebih tinggi akan sangat mungkin kamu peroleh, tergantung pada kemampuan dan pengalaman yang dimiliki, serta area tempat bekerja. Nah berikut ini beberapa pilihan karier yang bisa kamu geluti:'
}
const vm = new Vue({
    el: ".cover",
    data: konten
})

